# More details on how to configure the Travis build
# https://docs.travis-ci.com/user/customizing-the-build/

language: java

matrix:
  include:
    - jdk: oraclejdk8
      # Sanity regression tests with major supported Gradle versions
      env: SHIPKIT_REGRESSION_TESTS=quick

#don't build tags
branches:
  except:
  - /^v\d/

#Below skips the installation step completely (https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step)
install:
 - true

script:
  - ./gradlew build testDownstream -PcheckJava6Compatibility --daemon -s -i && ./gradlew ciPerformRelease -s

# Remove often changing files to prevent cache re-upload on no changes in dependencies
before_cache:
# pom, xml and jar files are known not to change
# assume non-whitelisted extensions are changing
# (this will include .lock, .bin, .metadata and potential future additions to gradle's caches folder)
  - find $HOME/.gradle/caches -type f -not \( -iname \*.pom -o -iname \*.jar -o -iname \*.xml \) -delete
# jar files which change
  - rm -fr $HOME/.gradle/caches/*/workerMain/gradle-worker.jar
# xml files which change
  - find $HOME/.gradle/caches/modules-2 -name ivy.xml -delete
# specific to shipkit build
  - rm -fr $HOME/.gradle/caches/jars-*/*/shipkit-*.jar
  - find $HOME/.gradle/caches/modules-2 -name shipkit-\*.jar -delete
# remove left over empty directories
  - find $HOME/.gradle/caches -type d -empty -delete
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
